language: python

install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.31.1/hugo_0.31.1_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    
script:
  - hugo # This commands builds your website on travis

after_success: |
    if [ -n "$GITHUB_API_KEY" ]; then
    git checkout --orphan master
    git rm -rf .
    mv public/* .
    rm -rf public hugo_*
    git add -f --ignore-errors --all
    git -c user.name='travis' -c user.email='travis' commit -m init
    git push -f -q https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG master
    fi
    