language: ruby

rvm:
    #- 2.2.7
    #- 2.3.4
  - 2.4.1
install:
  # Install binary pandoc from Rstudio
  # To use Pandoc, uncomment the following
  # - export PATH="$HOME/pandoc:$PATH"
  # - mkdir $HOME/pandoc
  # - curl -O https://s3.amazonaws.com/rstudio-buildtools/pandoc-1.12.3.zip
  # - unzip -j pandoc-1.12.3.zip pandoc-1.12.3/linux/debian/x86_64/pandoc
  #     -d $HOME/pandoc
  # - chmod +x $HOME/pandoc/pandoc
  # - pandoc --version

  # Install Jekyll and dependencies
  - bundle install

script: bundle exec rake site:deploy --quiet

