language: ruby
cache: bundler
rvm:
  - 2.3.4
  - 2.4.1
matrix:
  include:
  allow_failures:
    - rvm: 2.4.1
  fast_finish: true
install:
  - travis_retry bundle install
before_script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./release --only-4xx --assume-extension --check-favicon --check-html --allow-hash-href
script:
  - bundle exec rake site:deploy --quiet

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
