os: linux
dist: bionic
language: ruby
rvm: 2.7.0

addons:
  apt:
    packages:
      - libcurl4-openssl-dev  # to avoid SSL error (for htmlproofer)

# Overriding to drop the `--development` flag which requires the Gemfile.lock at build
install: bundle install --jobs=3 --retry=3 --path=vendor/bundle

before_script: git -C "$HOME" clone "$BUILDER_REPO" --depth=1 -q

jobs:
  include:
    - stage: Upgrade
      git:
        depth: false  # for posts' lastmod
      script: eval "$BUILD_CMD"
    - stage: Starter
      language: minimal
      install: true   # skip install step
      script: eval "$FLUSH_STARTER"
    - stage: Docs
      cache: bundler
      git:
        depth: false  # for posts' lastmod
      script: eval "$DOCS_CMD"

stages:
  - name: Upgrade
    if: branch = production
  - name: Starter
    if: branch = production
  - name: Docs
    if: branch = docs

notifications:
  email:
    recipients:
      - secure: "fFLqX7uOzFA8RE2AUFlU1mmxMw+rdV6DnODJ/1Gl+3ecNtrv5LeH3c5a4a5ShQqYTrx9BPfD40VRN7UB+lzOdXiWLI9yDGRPPxGG26/WfrKpdQPZilc8zAOEeDnLAJeGZLsUvgmNb3KCXW6S8NPqqh34CfWcTIzjCARhRgO33wcs8X5wP5cugtNqO5Ew/pUcfWcmiuXNX0GNT6l+nL5A7yN+IO5mRHqSRmlfYd5EHhGMTIL4La+Cd1CNv1m4Dl0Ah2cDeJwi5wLnVbqAgunLhAYmDtxIOCVYMTBrP37UiNe/7QeFelyJfODsmMg1mx3WCykbXydC753WVoAlTg6nNoeeI9fmK+/tuLK+sx/KnYfTVGBXQYq39DyV/2o/IfCzEAKImlzFKGD8R13+ddu4B5UML+cby5KBvhTKIGaC5tKoe39z/31UPpy11/EHMCof2BUOzIgu5Hsv4OSNJlw3oRE31oOPn8xP4e7uWR8bRUhAgzN0Cn0ht+UfpemfGAXrp0M3IXQdc9L4azEFqxRhivMTLK/P6INay7IM+DJ30Ht2dWylGw/sxcRTqyNm3YomJQnXIO4xeqTSLulWr80FFHTys3JEDJYrcKvJmpwLFEAOZtwKsZ6ZShrOIA4LE5fgQtakH3ZLJG9a7jVSlMcNIfaSKgjdDQOe6CoRQL7KouA="
    on_success: never

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
