# Configuration of Academic
# Documentation: https://sourcethemes.com/academic/

# The URL of your website.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "."

# Title of your site
title = "James E. Pustejovsky"

# Your copyright notice - appears in site footer.
# To display a copyright symbol, type `&copy;`.
copyright = "&copy; 2018"

theme = "hugo-academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
paginate = 10

# Enable comments by entering your Disqus shortname
disqusShortname = "jepusto"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
hasCJKLanguage = false  # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = false

# Get last modified date for content from Git?
enableGitInfo = false

[outputs]
  home = [ "HTML", "CSS", "RSS" ]
  section = [ "HTML", "RSS" ]

# Configure BlackFriday Markdown rendering.
#   See: https://gohugo.io/readfiles/bfconfig/
[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab.
  fractions = true  # `false` disables smart fractions (e.g. 5/12 formatted as a fraction).
  smartypants = true  # `false` disables all smart punctuation substitutions (e.g. smart quotes, dashes, fractions).

[params]
  # Color theme.
  #   Choose from `default`, `ocean`, `forest`, `coffee`, `dark`, or `1950s`.
  color_theme = "ocean"

  # Font style.
  #   Choose from `default`, `classic`, or `playfair`.
  font = "default"

  # Your details.
  name = "James E. Pustejovsky"
  role = "Assistant Professor"

  # Organizations/Affiliations.
  #   Separate multiple entries with a comma, using the form: `[ {name="Org1", url=""}, {name="Org2", url=""} ]`.
  organizations = [ { name = "University of Texas at Austin", url = "" } ]

  gravatar = false  # Get your avatar from Gravatar.com? (true/false)
  avatar = "James-headshot.jpg"  # Specify an avatar image (in `static/img/` folder) or delete value to disable avatar.
  email = "pusto@austin.utexas.edu"
  address = "University of Texas at Austin, 1912 Speedway, M/S D5800, Austin, TX 78712, USA"
  # office_hours = "Monday 10:00 to 13:00 or email for appointment"
  phone = "512 471 0683"
  skype = ""
  telegram = ""

  # Enable Keybase in Contact widget by entering your keybase.io username.
  keybase = ""

  # Discussion link (e.g. link to a forum, mailing list, or chat).
  #   Uncomment line below to use.
  #   discussion = { name = "Discuss", url = "https://discourse.gohugo.io" }

  # Diplay a logo in navigation bar rather than title (optional).
  #   To enable, place an image in `static/img/` and reference its filename below. To disable, set the value to "".
  logo = ""

  # Enable/disable map in Contact widget.
  # To show your address on a map in the contact widget, you need to enter your latitude, longitude and choose
  # a map provider below.
  # To use Google Maps, set `map = 1` and enter your API key that can be obtained here:
  #   https://developers.google.com/maps/documentation/javascript/get-api-key
  # To use OpenStreetMap tiles, set `map = 2`.
  # To use OpenStreetMap on a high traffic site, set `map = 3` and enter your API key that can be obtained here:
  #   https://www.mapbox.com/studio/account/tokens
  # To get your coordinates, right-click on Google Maps and choose "What's here?". The coords will show up at the bottom.
  #
  # Map provider:
  #   0: No map
  #   1: Google Maps
  #   2: OpenStreetMap (Mapnik)
  #   3: OpenStreetMap (Mapbox)
  map = 2
  map_api_key = ""
  latitude = "30.282891"
  longitude = "-97.738795"
  zoom = 15

  # Date and time format (refer to Go's date format: http://fuckinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "2006-01-02"
  #   Examples: "3:04 pm" or "15:04"
  time_format = "3:04 PM"

  # Show estimated reading time for posts?
  reading_time = false

  # Display comment count? Requires commenting to be enabled.
  comment_count = true

  # Display next/previous section pager?
  section_pager = false

  # Enable global LaTeX math rendering?
  #   If false, you can enable it locally on a per page basis.
  math = true

  # Highlight.js options
  #   highlight
  #     Enable global source code highlighting?  If false, you can
  #     override it for a particular page in that page's preamble.
  #
  #     Example: highlight = true
  #
  #   highlight_languages
  #     Add support for highlighting additional languages. Support for
  #     languages mentioned here will be included in all pages. You
  #     can also set this variable for a particular page in that
  #     page's preamble.
  #
  #     Example: highlight_languages = ["go", "lisp", "ocaml"]
  #
  #   highlight_style
  #     Choose a different CSS style for highlighting source
  #     code. Setting this option in a page's preamble has no
  #     effect.
  #
  #     Example: highlight_style = "github-gist"
  #
  #   For the list of supported languages and styles, see:
  #   https://cdnjs.com/libraries/highlight.js/
  #
  #   For more info on the highlighting options, see:
  #   https://sourcethemes.com/academic/post/writing-markdown-latex/#highlighting-options
  highlight = true
  highlight_languages = []
  # highlight_style = "github"

  # Enable native social sharing buttons?
  sharing = true

  # Privacy pack
  #   Show a cookie consent message to visitors
  #   Anonymize IP in Google Analytics (if enabled)
  privacy_pack = false

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []

  # Publication types.
  #   Used to categorize publications.
  #   The index of the publication type in the list is used as its unique numerical identifier.
  #   The numeric ID is used in a publication's frontmatter to categorize it.
  #   The language can be edited below.
  #   For multilingual sites, `publication_types` can be copied to each language section at the end of this file and
  #   translated.
  publication_types = [
    'Uncategorized',  # 0
    'Conference paper',  # 1
    'Journal article',  # 2
    'Manuscript',  # 3
    'Report',  # 4
    'Book',  # 5
    'Book section'  # 6
  ]

[permalinks]
    post = "/:slug"
    
  # Configuration of talk pages.
  [params.talks]
    # Show talk time?
    time = true

  # Configuration of publication pages.
  [params.publications]
    # Date format (refer to Go's date format: http://fuckinggodateformat.com )
    #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
    date_format = "January, 2006"

  # Configuration of project pages.
  [params.projects]
    # List publications and talks related to the project?
    list_children = true

    # Publication list format.
    #   0 = Simple
    #   1 = Detailed
    #   2 = APA
    #   3 = MLA
    publication_format = 2

  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fa" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:pusto@austin.utexas.edu"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "//twitter.com/jepusto"

  [[params.social]]
    icon = "google-scholar"
    icon_pack = "ai"
    link = "https://scholar.google.com/citations?user=vrPDTgsAAAAJ"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/jepusto"


# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
[params.menus]
  # Align the main menu to the right of the page? (true/false)
  align_right = false

[[menu.main]]
  name = "Posts"
  url = "#posts"
  weight = 2

[[menu.main]]
  name = "Publications"
  url = "#publications"
  weight = 3

[[menu.main]]
  name = "Presentations"
  url = "#talks"
  weight = 4

[[menu.main]]
  name = "Software"
  url = "#software"
  weight = 5

[[menu.main]]
  name = "Teaching"
  url = "#teaching"
  weight = 6

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 7

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"

# Languages
#   Create a [languages.X] block for each language you want, where X is the language ID.

# Configure the English version of the website.
[Languages.en]
  languageCode = "en-us"
