baseURL = "https://chrisrichards.co.uk/"
languageCode = "en-gb"
title = "Chris Richards"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Chris Richards"
  facebook = ""
  twitter = "https://twitter.com/crichards2000"
  instagram = ""
  youtube = ""
  github = "https://github.com/chrisrichards"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/chris-richards-52a5481/"
  mastodon = ""
  slack = ""
  stackoverflow = "https://stackoverflow.com/users/251441/chrisr"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
