environment:
  nodejs_version: 8
  RACK_ENV: test
  JEKYLL_LOG_LEVEL: warn
  RUBY_VERSION: 24
  matrix:
    - TEST_SUITE: node
    - TEST_SUITE: ruby

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - ps: Install-Product node $env:nodejs_version
  - gem update --system --no-document
  - bundle config --local path vendor/bundle
  - sh script/bootstrap

build: off

branches:
  only:
    - master

before_test:
  - node --version
  - npm --version
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - sh script/cibuild

cache:
  - vendor/bundle
  - 'node_modules -> package.json' # invalidate cache if package.json changes

init:
  - git config --global core.autocrlf true
